environment:

    matrix:
        - PYTHON: "C:\\Python35"
          PYTHON_VERSION: "3.5.x"
          PYTHON_ARCH: "32"
          TOXENV: "py35,py35-compress"
          TOX_APPVEYOR_X64: 0
          TOX_H5PY_REQIREMENTS: "requirements32.txt"

        - PYTHON: "C:\\Python35-x64"
          PYTHON_VERSION: "3.5.x"
          PYTHON_ARCH: "64"
          TOXENV: "py35,py35-compress"
          TOX_APPVEYOR_X64: 1

        - PYTHON: "C:\\Python36"
          PYTHON_VERSION: "3.6.x"
          PYTHON_ARCH: "32"
          TOXENV: "py36,py36-compress"
          TOX_APPVEYOR_X64: 0
          TOX_H5PY_REQIREMENTS: "requirements32.txt"

        - PYTHON: "C:\\Python36-x64"
          PYTHON_VERSION: "3.6.x"
          PYTHON_ARCH: "64"
          TOXENV: "py36,py36-compress"
          TOX_APPVEYOR_X64: 1

        - PYTHON: "C:\\Python37"
          PYTHON_VERSION: "3.7.x"
          PYTHON_ARCH: "32"
          TOXENV: "py37,py37-compress"
          TOX_APPVEYOR_X64: 0
          TOX_H5PY_REQIREMENTS: "requirements32.txt"

        - PYTHON: "C:\\Python37-x64"
          PYTHON_VERSION: "3.7.x"
          PYTHON_ARCH: "64"
          TOXENV: "py37,py37-compress"
          TOX_APPVEYOR_X64: 1

        - PYTHON: "C:\\Python38"
          PYTHON_VERSION: "3.8.x"
          PYTHON_ARCH: "32"
          TOXENV: "py38,py38-compress"
          TOX_APPVEYOR_X64: 0
          TOX_H5PY_REQIREMENTS: "requirements32.txt"

        - PYTHON: "C:\\Python38-x64"
          PYTHON_VERSION: "3.8.x"
          PYTHON_ARCH: "64"
          TOXENV: "py38,py38-compress"
          TOX_APPVEYOR_X64: 1

install:
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Upgrade pip
    - "python -m pip install --user --upgrade pip setuptools wheel virtualenv"

    # install tox and tox-appveryor
    - "python -m pip install tox tox-appveyor"

build: false

test_script:
    #- "check-manifest"
    - "python -m tox"
    #- "python setup.py sdist bdist_wheel"
    #- "twine check dist/*"
    #- "pip install ."
    #- "pytest"
